packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry/cli'
  - bcrypt
  - core-js
  - esbuild
  - msgpackr-extract
  - prisma
  - protobufjs
